name: Secrets Vault Action E2E Test

on:
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch secret using username/password authentication
        id: fetch-secret
        uses: EntrustCorporation/secrets-vault-action@v1
        with:
          base_url: ${{ secrets.BASE_URL }}
          auth_type: 'userpass'
          username: ${{ secrets.VAULT_USERNAME }}
          password: ${{ secrets.VAULT_PASSWORD }}
          vault_uid: ${{ secrets.VAULT_UID }}
          ca_cert: ${{ secrets.CA_CERT }}
          secrets: |
            Box1.accessKey | AWS_ACCESS_KEY_ID;
            Box1.SimpleKVSecret | SIMPLE_KV_SECRET;
            Box1.ExampleTextSecret | EXAMPLE_TEXT_SECRET;
            Box1-afe7d9.privateKey-48122e | PRIVATE_KEY;
            Box2.StripeKey | STRIPE_KEY;
            Box1.DOCKER_USERNAME | DOCKER_USERNAME;
            Box1.DOCKER_PASSWORD | DOCKER_PASSWORD;

      - name: Compare secrets with GitHub secrets
        run: |
          echo '${{ toJson(steps.fetch-secret.outputs) }}' > example.json

          cat example.json

          if [[ "${{ steps.fetch-secret.outputs.AWS_ACCESS_KEY_ID }}" != "${{ secrets.AWS_ACCESS_KEY_ID }}" ]]; then
            echo "AWS_ACCESS_KEY_ID does not match!"
            exit 1
          fi
          if [[ "${{ steps.fetch-secret.outputs.PRIVATE_KEY }}" != "${{ secrets.PRIVATE_KEY }}" ]]; then
            echo "PRIVATE_KEY does not match!"
            exit 1
          fi
          if [[ "${{ steps.fetch-secret.outputs.STRIPE_KEY }}" != "${{ secrets.STRIPE_KEY }}" ]]; then
            echo "STRIPE_KEY does not match!"
            exit 1
          fi
          if [[ "${{ steps.fetch-secret.outputs.DOCKER_USERNAME }}" != "${{ secrets.DOCKER_USERNAME }}" ]]; then
            echo "DOCKER_USERNAME does not match!"
            exit 1
          fi
          if [[ "${{ steps.fetch-secret.outputs.DOCKER_PASSWORD }}" != "${{ secrets.DOCKER_PASSWORD }}" ]]; then
            echo "DOCKER_PASSWORD does not match!"
            exit 1
          fi
          if [[ "${{ steps.fetch-secret.outputs.EXAMPLE_TEXT_SECRET }}" != "${{ secrets.EXAMPLE_TEXT_SECRET }}" ]]; then
            echo "EXAMPLE_TEXT_SECRET does not match!"
            exit 1
          fi
          echo ${SIMPLE_KV_SECRET} | base64
          if [[ "${{ steps.fetch-secret.outputs.SIMPLE_KV_SECRET }}" != "${{ secrets.SIMPLE_KV_SECRET }}" ]]; then
            echo "SIMPLE_KV_SECRET does not match!"
            exit 1
          fi
          echo "All secrets match successfully!"
  
      - name: Clean up
        if: always()  # Run even if previous steps fail
        run: |
          # Securely remove sensitive files - DO NOT SKIP THIS STEP
          shred -u example.json